[package]
authors = ["Ned Ruggeri <ruggeri@self-loop.com>"]
name = "fourier2"
version = "0.1.0"
[dependencies]
byteorder = "1.2.3"
clap = "2.31.2"
derive_builder = "0.5.1"
rand = "0.5.0"

[[bin]]
name = "fourier2"
path = "src/cli/mod.rs"

[lib]
name = "fourier2"
path = "src/lib/mod.rs"
